name: backend deployment

on:
 push:
  paths:
   - "SpendSense-BackEnd/**"

jobs:
 deploy:
  environment: Prod
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   
   - name: Setup Java
     uses: actions/setup-java@v4
     with: 
      distribution: temurin
      java-version: 21

   - name: Build backend
     run: |
      cd SpendSense-BackEnd
      ./mvnw clean package -DskipTests

   - name: Copy JAR to EC2
     uses: appleboy/scp-action@v0.1.7
     with: 
      host: ${{ secrets.EC2_HOST }}
      username: ubuntu
      key: ${{ secrets.EC2_SSH_KEY }}
      source: "SpendSense-BackEnd/target/app.jar"
      strip_components: 2
      target: "/home/ubuntu/apps/SpendCents/"

   - name: Copy Infra config to EC2
     uses: appleboy/scp-action@v0.1.7
     with: 
      host: ${{ secrets.EC2_HOST }}
      username: ubuntu
      key: ${{ secrets.EC2_SSH_KEY }}
      source: SpendSense-BackEnd/Dockerfile,SpendSense-BackEnd/compose.yaml
      strip_components: 1
      target: "/home/ubuntu/apps/SpendCents/"

   - name: Rebuild backend on EC2
     uses: appleboy/ssh-action@v1.0.3
     with:
      host: ${{ secrets.EC2_HOST }}
      username: ubuntu 
      key: ${{ secrets.EC2_SSH_KEY }}
      script: |
        cd /home/ubuntu/apps/SpendCents/
        docker compose down
        docker compose up -d
